version: "3.8"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: escuela
    container_name: escuela-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - escuela

  db:
    image: mysql:5.7
    container_name: escuela-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - escuela

  nginx:
    image: nginx:alpine
    container_name: escuela-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - escuela

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: "http://localhost:8000/swagger.yaml"
    ports:
      - "8080:8080"
    networks:
      - escuela

networks:
  escuela:
    driver: bridge